# Generated by Django 4.0.5 on 2022-07-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoData',
            fields=[
                ('crypto_name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='id name of cryptocurrency')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='cost of cryptocurrency')),
                ('human_name', models.CharField(max_length=50, unique=True, verbose_name='humanazed name of cryptocurrency')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email adress')),
                ('first_name', models.CharField(blank=True, default='Person', help_text='Please, enter your name', max_length=50, verbose_name='first name')),
                ('pocket', models.JSONField(verbose_name='user pocket')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
